import { z } from "zod";
import { PageRecord, pageRecordSchema } from "./schema";
import { mergeRecords } from "./read-model";

// Accountless end-to-end encrypted sync. One random secret, generated on the first
// device and pasted onto the others, is the only identity in the system. Three values
// derive from it with HKDF-SHA256 under distinct info strings:
//
//   sync id     public; names the blob on the server
//   auth token  bearer write-token; the server stores only its SHA-256 hash
//   enc key     AES-256-GCM; never serialized, never leaves the device
//
// The server holds ciphertext and a token hash. It can withhold service, but it can
// never read, and nothing ties the blob to a person. Losing the secret loses the data;
// that is the honest price of the design, and local data plus JSON export remain.

export const syncPayloadSchema = z.object({
  v: z.literal(1),
  exportedAt: z.string(),
  pages: z.array(pageRecordSchema),
});

// The server-side ceiling on one ciphertext blob. Clients must trim what they upload
// to fit under it (the extension drops the oldest-visited pages from the sync payload,
// never from local storage) instead of letting every PUT die on a 400 forever.
export const SYNC_DATA_MAX_CHARS = 8_000_000;

export const syncEnvelopeSchema = z.object({
  version: z.number().int().nonnegative(),
  iv:   z.string().max(64),
  data: z.string().max(SYNC_DATA_MAX_CHARS),
});

export const syncPutRequestSchema = z.object({
  expectedVersion: z.number().int().nonnegative(), // 0 registers a fresh sync id
  iv:   z.string().max(64),
  data: z.string().max(SYNC_DATA_MAX_CHARS),
});

export type SyncPayload    = z.infer<typeof syncPayloadSchema>;
export type SyncEnvelope   = z.infer<typeof syncEnvelopeSchema>;
export type SyncPutRequest = z.infer<typeof syncPutRequestSchema>;

export type SyncKeys = {
  syncId:    string;
  authToken: string;
  encKey:    CryptoKey;
};

export function generateSyncSecret(): string {
  return toBase64Url(crypto.getRandomValues(new Uint8Array(32)));
}

// A sync key is either generated by us (base64url of 32 random bytes) or brought by
// the user from a password manager's generator. Brought keys must clear a strength
// gate: the key alone locates AND unlocks the data, and a guessed key is verifiable
// against the server, so anything memorable or word-based is not accepted. The gate
// is charset-model entropy, which flatters dictionary phrases; the three-classes
// requirement is what keeps those out.
export const SECRET_MIN_LENGTH  = 16;
export const SECRET_MIN_CLASSES = 3;
export const SECRET_MIN_BITS    = 80;

export type SecretStrength =
  | { kind: "generated" }
  | { kind: "strong-text"; bits: number }
  | { kind: "weak"; reason: "too-short" | "has-spaces" | "too-uniform" | "too-guessable" };

export function secretStrength(secret: string): SecretStrength {
  const s = secret.trim();

  const raw = fromBase64Url(s);
  if (raw !== null && raw.length >= 16) return { kind: "generated" };

  // Whitespace means a word phrase, and word phrases are guessable no matter what the
  // charset arithmetic below claims. The symbol requirement exists for the same reason:
  // it is what separates a generator's output from a memorable camel-case sentence.
  if (s.length < SECRET_MIN_LENGTH) return { kind: "weak", reason: "too-short" };
  if (/\s/.test(s))                 return { kind: "weak", reason: "has-spaces" };
  if (!/[^a-zA-Z0-9]/.test(s))      return { kind: "weak", reason: "too-uniform" };

  const classes = [/[a-z]/, /[A-Z]/, /[0-9]/, /[^a-zA-Z0-9]/].filter((re) => re.test(s)).length;
  const charset = (/[a-z]/.test(s) ? 26 : 0)
                + (/[A-Z]/.test(s) ? 26 : 0)
                + (/[0-9]/.test(s) ? 10 : 0)
                + (/[^a-zA-Z0-9]/.test(s) ? 33 : 0);
  const bits = s.length * Math.log2(Math.max(charset, 1));

  if (classes < SECRET_MIN_CLASSES) return { kind: "weak", reason: "too-uniform" };
  if (bits < SECRET_MIN_BITS)       return { kind: "weak", reason: "too-guessable" };

  return { kind: "strong-text", bits };
}

/** Null for anything the strength gate rejects; see secretStrength for the rules. */
export async function deriveSyncKeys(secret: string): Promise<SyncKeys | null> {
  const s = secret.trim();
  const strength = secretStrength(s);
  if (strength.kind === "weak") return null;

  // Generated keys are already uniform randomness and feed HKDF directly; this path
  // must stay stable forever or existing users lose their blobs. Brought text runs
  // through PBKDF2 first, so even a leaked ciphertext is slow to attack offline.
  const ikm = strength.kind === "generated"
    ? ensureBytes(fromBase64Url(s))
    : new Uint8Array(await crypto.subtle.deriveBits(
        { name: "PBKDF2", hash: "SHA-256", salt: new TextEncoder().encode("swdi-sync-text-v1"), iterations: 310_000 },
        await crypto.subtle.importKey("raw", new TextEncoder().encode(s), "PBKDF2", false, ["deriveBits"]),
        256,
      ));

  const master = await crypto.subtle.importKey("raw", ikm, "HKDF", false, ["deriveBits", "deriveKey"]);

  const idBits    = await crypto.subtle.deriveBits(hkdf("swdi-sync-id-v1"), master, 128);
  const tokenBits = await crypto.subtle.deriveBits(hkdf("swdi-auth-token-v1"), master, 256);
  const encKey    = await crypto.subtle.deriveKey(
    hkdf("swdi-enc-key-v1"),
    master,
    { name: "AES-GCM", length: 256 },
    false,
    ["encrypt", "decrypt"],
  );

  return { syncId: toHex(new Uint8Array(idBits)), authToken: toBase64Url(new Uint8Array(tokenBits)), encKey };
}

function ensureBytes(bytes: Uint8Array<ArrayBuffer> | null): Uint8Array<ArrayBuffer> {
  if (bytes === null) throw new Error("secretStrength said generated, decode disagreed");

  return bytes;
}

export async function encryptPayload(encKey: CryptoKey, payload: SyncPayload): Promise<{ iv: string; data: string }> {
  const iv    = crypto.getRandomValues(new Uint8Array(12));
  const bytes = await gzipBytes(new TextEncoder().encode(JSON.stringify(payload)));

  const ciphertext = await crypto.subtle.encrypt({ name: "AES-GCM", iv }, encKey, bytes);
  return { iv: toBase64Url(iv), data: toBase64Url(new Uint8Array(ciphertext)) };
}

/** Null on a wrong key, tampered ciphertext, or a payload that fails the schema. */
export async function decryptPayload(encKey: CryptoKey, iv: string, data: string): Promise<SyncPayload | null> {
  const ivBytes   = fromBase64Url(iv);
  const dataBytes = fromBase64Url(data);
  if (ivBytes === null || dataBytes === null) return null;

  let plaintext: Uint8Array;
  try   { plaintext = new Uint8Array(await crypto.subtle.decrypt({ name: "AES-GCM", iv: ivBytes }, encKey, dataBytes)); }
  catch { return null; }

  // Payloads are gzipped before encryption (JSON reading records compress ~5x, which
  // is headroom against the server's size cap). Blobs written before compression
  // landed hold plain JSON; the gzip magic bytes tell them apart.
  if (plaintext[0] === 0x1f && plaintext[1] === 0x8b) {
    try   { plaintext = await gunzipBytes(plaintext); }
    catch { return null; }
  }

  let json: unknown;
  try   { json = JSON.parse(new TextDecoder().decode(plaintext)); }
  catch { return null; }

  const parsed = syncPayloadSchema.safeParse(json);
  return parsed.success ? parsed.data : null;
}

async function gzipBytes(bytes: Uint8Array): Promise<Uint8Array<ArrayBuffer>> {
  const stream = new Blob([bytes as BlobPart]).stream().pipeThrough(new CompressionStream("gzip"));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

async function gunzipBytes(bytes: Uint8Array): Promise<Uint8Array<ArrayBuffer>> {
  const stream = new Blob([bytes as BlobPart]).stream().pipeThrough(new DecompressionStream("gzip"));
  return new Uint8Array(await new Response(stream).arrayBuffer());
}

/**
 * Union of two page sets, one record per url. When both sides carry a page, the copy
 * with the newer visit contributes the outline and title, and mergeRecords folds the
 * other side's reads and sightings in.
 */
export function mergePages(a: PageRecord[], b: PageRecord[]): PageRecord[] {
  const byUrl = new Map<string, PageRecord>();
  for (const record of a) byUrl.set(record.url, record);

  for (const record of b) {
    const existing = byUrl.get(record.url);
    if (existing === undefined) { byUrl.set(record.url, record); continue; }

    const [base, other] = existing.lastVisitAt >= record.lastVisitAt ? [existing, record] : [record, existing];
    mergeRecords(base, other);
    byUrl.set(base.url, base);
  }

  return [...byUrl.values()];
}

// The secret is already uniform randomness, so a fixed zero salt is fine; the info
// strings are what separate the derived values.
function hkdf(info: string): HkdfParams {
  return { name: "HKDF", hash: "SHA-256", salt: new Uint8Array(32), info: new TextEncoder().encode(info) };
}

function toHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, "0")).join("");
}

function toBase64Url(bytes: Uint8Array): string {
  let binary = "";
  for (let i = 0; i < bytes.length; i += 0x8000) {
    binary += String.fromCharCode(...bytes.subarray(i, i + 0x8000));
  }

  return btoa(binary).replaceAll("+", "-").replaceAll("/", "_").replace(/=+$/, "");
}

function fromBase64Url(text: string): Uint8Array<ArrayBuffer> | null {
  // Strictly the canonical alphabet: atob's forgiving-base64 strips whitespace, which
  // would let word phrases masquerade as generated keys and take the wrong path.
  if (!/^[A-Za-z0-9_-]+$/.test(text)) return null;

  const base64 = text.replaceAll("-", "+").replaceAll("_", "/");

  let binary: string;
  try   { binary = atob(base64); }
  catch { return null; }

  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);

  return bytes;
}
